# Generated by Django 6.0.6 on 2026-06-26 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participante_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('local', models.CharField(blank=True, max_length=160, verbose_name='Local')),
                ('vagas', models.PositiveIntegerField(default=0, verbose_name='Quantidade de vagas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='participante',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participantes', to='core.evento', verbose_name='Evento'),
        ),
    ]
